<?php
	$tenmaychu='localhost';
	$taikhoan='root';
	$matkhau='';
	$csdl='webtintuc';
    $port=null;
    $socket="/cloudsql/projectwebtintuc:us-central1:csdlwebtintuc";
    $connect=mysqli_connect($tenmaychu,$taikhoan,$matkhau,$csdl,$port,$socket);
	mysqli_select_db($connect,$csdl);
?>