<?php
	$tenmaychu='localhost';
	$taikhoan='root';
	$matkhau='';
	$csdl='webtintuc';
	$port=null;
	$socket="/cloudsql/news-238114:us-central1:websitetintuc";
	$connect=mysqli_connect($tenmaychu,$taikhoan,$matkhau,$csdl,$port,$socket);
	mysqli_select_db($connect,$csdl);
?>