applcation: smsystem-1353
version: 1
runtime: php55
api-version: 1
threadsafe: yes

handlers:
  - url: /favicon\.ico
    static_files: favicon.ico
    upload: favicon\.ico

  - url: .*
    script: index.php
